### ISSUE TITLE
Boa tarde Matheus

### ISSUE THREAD

**Issue by alissonandrade2020** [MatheusPires99/gobarber-2.0#5]
Como faço para rodar o Backend ?? lá falar em docker ??? ou é só seguir o passo a passo do Backend que você colocou lá ??

**Comment by alissonandrade2020** [comment]
ERRO :  λ yarn typeorm migration:run
yarn run v1.22.4
$ ts-node-dev -r tsconfig-paths/register ./node_modules/typeorm/cli.js migration:run
Using ts-node version 8.8.2, typescript version 3.8.3
Error during migration run:
Error: No connection options were found in any orm configuration files.
    at ConnectionOptionsReader.<anonymous> (C:\gobarber20\backend\src\connection\ConnectionOptionsReader.ts:41:19)
    at step (C:\gobarber20\backend\node_modules\tslib\tslib.js:139:27)
    at Object.next (C:\gobarber20\backend\node_modules\tslib\tslib.js:120:57)
    at fulfilled (C:\gobarber20\backend\node_modules\tslib\tslib.js:110:62)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by MatheusPires99** [comment]
@alissonandrade2020 você precisa subir uma imagem no docker do Postgres, redis e mongo. Os nomes que você colocar para essas imagens, senhas e portas são as variáveis que você irá preencher no .env da aplicação.

**Comment by alissonandrade2020** [comment]
pode me enviar um exemplo ? :)

Get Outlook for Android<https://aka.ms/ghei36>
________________________________

**Comment by alissonandrade2020** [comment]
Aqui só tem isso >> APP_SECRET=

APP_WEB_URL=http://localhost:3000
APP_API_URL=http://localhost:3333

# Redis
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASS=


Se você puder enviar um fictício ;]

**Comment by MatheusPires99** [comment]
@alissonandrade2020 desculpa a demora, na verdade você não precisa subir imagem do Mongo, apenas Postgres e Redis, e no .env você vai preencher as informações apenas do APP_SECRET e o REDIS_PASS caso seu container do Redis tenha uma senha. Com isso sua aplicação deve rodar tranquilamente.

**Comment by alissonandrade2020** [comment]
Tranquilo, no caso a imagem no docker né isso ? tem como passar o comandos, já esqueci, rsrs

Aqui só tem isso >> APP_SECRET=

APP_WEB_URL=http://localhost:3000
APP_API_URL=http://localhost:3333

Redis
REDIS_HOST=localhost
REDIS_PORT=6379
REDIS_PASS=

não sei, dá uma luz, rsrs

**Comment by MatheusPires99** [comment]
Tenta com rodando esses comandos no terminal, tanto pro Postgres quanto Redis. O APP_SECRET é pra vc preencher ele com uma string totalmente aleatória mesmo (você pode usar esse site https://www.md5hashgenerator.com/, digitar um texto qualquer que ele vai gerar um string aleatória para você)

Redis: docker run --name NOME_CONTAINER -p 6379:6379 -d -t redis:alpine
Postgres: docker run --name NOME_CONTAINER -e POSTGRES_PASSWORD=SENHA_CONTAINER -p 5432:5432 -d postgres

**Comment by alissonandrade2020** [comment]
Valeu cara, ei tá fazendo o nextlevel 2 ???

**Comment by MatheusPires99** [comment]
Vou ver se acho um tempinho pra fazer hahah
